#! /bin/sh
img=mcluseau/tftpd-hpa

set -e

docker build -t $img .
v=$(docker run --rm -it --entrypoint apk mcluseau/tftpd-hpa info tftp-hpa -d |head -n 1 |cut -d' ' -f1 |cut -d- -f3-)

echo "-> version: $v"
echo "tagging as $img:$v"

docker tag $img $img:$v

docker push $img:$v
docker push $img
